env:
  es2021: true
  jest: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
plugins:
  - jest
